import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/_components/Navbar'
import cn from 'classnames'
import Providers from './providers'
import AboutMe from './_components/AboutMe'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(roboto.className, 'bg-primary')}>
        <Providers>
          <Navbar />
          <AboutMe/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
